---
- hosts: all
  remote_user: ubuntu
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - name: set hostname
    hostname:
      name: web01
  - name: install nginx
    apt: 
      name: nginx
      state: present
      update_cache: yes
  - name: configure nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: clone html app repo
    ansible.builtin.git:
      repo: https://github.com/schoolofdevops/html-sample-app.git
      dest: /var/www/html/app
  
